# Automatically updated by the winget bot at 2021/Nov/04
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Mailbird.Mailbird
PackageVersion: 2.9.47
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallerSwitches:
  Silent: /exenoui /qn /norestart
  SilentWithProgress: /exenoui /qn /norestart
UpgradeBehavior: install
Commands:
- mailbird
FileExtensions:
- eml
Installers:
- Architecture: x64
  InstallerUrl: https://download.getmailbird.com/installers/MailbirdSetup.exe
  InstallerSha256: A78679068CFC0AB2C0AFAFC54E466E29F1C6FB3BB979B598E1E418A2470F3958
ManifestType: installer
ManifestVersion: 1.0.0
