# Automatically updated by the winget bot at 2021/Nov/04
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json

PackageIdentifier: MabelisYT.MabelTermSnapshot
PackageVersion: 1.1.5.0
DefaultLocale: en-GB
ManifestType: version
ManifestVersion: 1.0.0
