# Automatically updated by the winget bot at 2021/Nov/03
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: DigiDNA.iMazing
PackageVersion: 2.14.5.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://downloads.imazing.com/windows/iMazing/iMazing2forWindows.exe
  InstallerSha256: 504272DE2F8F616898061BD96A5BFF4A7123845B38AF438A52B161F28B0A6BCD
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
