# Automatically updated by the winget bot at 2021/Nov/04
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: TopalaSoftwareSolutions.SIW
PackageVersion: 2021.08.24.9
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 6.1.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://siw64.com/download/siwtrial-setup.exe
  InstallerSha256: 317A64F3D5C497A0A070874D1AE4D4E6BBA378C921193A8E8EFA5357A4F852F6
ManifestType: installer
ManifestVersion: 1.0.0
