# Automatically updated by the winget bot at 2021/Nov/04
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: TopalaSoftwareSolutions.SIW
PackageVersion: 2021.08.24.9
PackageLocale: en-US
Publisher: Topala Software Solutions
PublisherUrl: https://www.gtopala.com
PublisherSupportUrl: https://www.gtopala.com/forum/
PrivacyUrl: https://www.gtopala.com/tss/privacy-policy.php
Author: Gabriel Topala
PackageName: SIW
PackageUrl: https://www.gtopala.com
License: Commercial
LicenseUrl: https://www.gtopala.com/agreement/
Copyright: © 2005-2021 Topala Software Solutions
CopyrightUrl: https://www.gtopala.com/agreement/
ShortDescription: System Information for Windows - Everything you want to know about your computer
Description: SIW is an advanced System Information for Windows tool that analyzes your computer and gathers detailed information about system properties and settings (Software Information, Hardware Information, Network Information, and Tools). It displays it in a highly comprehensible manner.
Moniker: siw
Tags:
- trail
- system-information
- hardware
- software
- network
- memory
- intel
- amd
- processor
- cpu
- motherboard
ManifestType: defaultLocale
ManifestVersion: 1.0.0
