# Automatically updated by the winget bot at 2021/Nov/03
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: GlassWire.GlassWire
PackageVersion: 2.3.363.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2017Redist-x86
Installers:
- Architecture: x64
  InstallerUrl: https://download.glasswire.com/GlassWireSetup.exe
  InstallerSha256: 56B49894356F343B844DE2951F2FEE3266322D95325CD270666856EC5FC828CD
ManifestType: installer
ManifestVersion: 1.0.0
